# Custom network configuration
network:
    version: 2
    ethernets:
        eth0:
            dhcp4: false
            dhcp6: false
            addresses:
              - 10.10.10.250/24
              - 2001:dbf:0:1::250/64
            gateway4: 10.10.10.1
            gateway6: 2001:dbf:0:1::1
            nameservers:
              addresses:
                - 8.8.8.8
            routes:
              - to: 10.100.200.0/24
                via: 10.10.10.100
                metric: 0
              - to: 10.107.200.0/24
                via: 10.10.10.107
                metric: 0
              - to: 10.108.200.0/24
                via: 10.10.10.108
                metric: 0
              - to: 10.120.200.0/24
                via: 10.10.10.120
                metric: 0
              - to: 10.177.200.0/24
                via: 10.10.10.109
                metric: 0
              - to: 10.178.200.0/24
                via: 10.10.10.109
                metric: 0
